travis:
  secure:
    BINSTAR_TOKEN: tUhO0iOWsuJxO0wC8MgFtdaDQIhkVY8qgNrRpTkqP7/+DMRR6V+uc6zMtBgl/gMnDAKPVGikC0i9py+1nWlzkOR8ImgVahWY4iFFT9czfzv/4aXo/zV65md5SVTjejnlEL81jbUBTVGNGVMdx0SJPT3EKjjTVfTeO7BMOYE/IOzhBHsHaTJyoDoiM/LI6oyGWP3Bkagr/NMeeZNlwxIbGVZpo68PpO8Fpsh+UcAr707wh+untDmun1TB6970ki4kl8aBotcoSUfZKQqx+bJhn4XcO0QHVYLGqznMMLlI13BgzJ4/eTcg1IaOdFBGIrq9wnfagXd/phanBIBhWVc0Gk8zJ0KuvsxErCa6Xsi5o5FqEDmH+GzKV8YjmuEV42AhfJW8nP8XjWdl9QcC7QjYFUDQfKPca4Emomg4s3lpWDDxPlAHGolwIsRjbE15VHpQ5edrooMu8Cncq7IPVFbHR+5BnFcq4IMncYP44fgkjWOs6frs7CqWkKnjpRxhkHVrolmteVQ6JefO0JgZDiK2lY7eeJm7y2xkeTucUPWUvvRnxbBQRjHu5mdVJb+m2vDSxpcE9qCxj5ynmqfXjnZvyP9S2kxzTw+0PWOXAmnP3P4lVI9r+3B/wUk4vyxHhZQlFV6OiPfy31t/RjM0kzTm+ROSvWrevgKygLJmffztrcA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
